'use client'

import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from 'react'
import { FolderTree, ImagePlus, LoaderCircle, LogOut, Pencil, Plus, Search, SlidersHorizontal, Sparkles, Trash2 } from 'lucide-react'
import { applyFloralEffects, defaultFloralEffects, floralEffectsStorageKey, normalizeFloralEffects, type FloralControl, type FloralEffects } from '@/components/effects-controller'
import { createSupabaseClient, isSupabaseConfigured } from '@/lib/supabase'
import { formatPrice, type Product, type ProductInput } from '@/lib/products'
import { createProduct, deleteProduct, getProducts, updateProduct, uploadProductImage } from '@/services/products'
import { createTaxonomy, deleteTaxonomy, getTaxonomies, type Taxonomy, updateTaxonomy } from '@/services/taxonomies'

type View = 'products' | 'categories' | 'essences' | 'effects'
type TaxonomyKind = 'categories' | 'essences'
const blank: ProductInput = { name: '', description: '', price: 0, category: '', essence: '', detail: '', active: true, imageUrl: null }
const isAdmin = (metadata: Record<string, unknown> | undefined) => metadata?.role === 'admin'

export function AdminDashboard() {
  const [ready, setReady] = useState(false), [logged, setLogged] = useState(false), [view, setView] = useState<View>('products')
  const [products, setProducts] = useState<Product[]>([]), [categories, setCategories] = useState<Taxonomy[]>([]), [essences, setEssences] = useState<Taxonomy[]>([])
  const [loading, setLoading] = useState(false), [message, setMessage] = useState(''), [error, setError] = useState(false)
  const [query, setQuery] = useState(''), [status, setStatus] = useState('all'), [categoryFilter, setCategoryFilter] = useState('all')
  const [login, setLogin] = useState({ email: '', password: '' }), [form, setForm] = useState<ProductInput | null>(null), [editing, setEditing] = useState<Product | null>(null)
  const [effects, setEffects] = useState<FloralEffects>(defaultFloralEffects), [effectsReady, setEffectsReady] = useState(false)
  const say = (text: string, bad = false) => { setMessage(text); setError(bad); window.setTimeout(() => setMessage(''), 4000) }
  const load = async () => { setLoading(true); try { const [p, c, e] = await Promise.all([getProducts(), getTaxonomies('categories'), getTaxonomies('essences')]); setProducts(p); setCategories(c); setEssences(e) } catch (cause) { say(cause instanceof Error ? cause.message : 'Falha ao carregar catálogo.', true) } finally { setLoading(false) } }
  useEffect(() => { if (!isSupabaseConfigured) { setReady(true); return }; createSupabaseClient().auth.getUser().then(({ data }) => { const allowed = Boolean(data.user && isAdmin(data.user.app_metadata)); setLogged(allowed); setReady(true); if (allowed) void load() }) }, [])
  useEffect(() => { try { const saved = window.localStorage.getItem(floralEffectsStorageKey); if (saved) setEffects(normalizeFloralEffects(JSON.parse(saved))) } finally { setEffectsReady(true) } }, [])
  useEffect(() => { if (!effectsReady) return; applyFloralEffects(effects); window.localStorage.setItem(floralEffectsStorageKey, JSON.stringify(effects)) }, [effects, effectsReady])
  const filtered = useMemo(() => products.filter((p) => `${p.name} ${p.category ?? ''} ${p.essence ?? ''}`.toLowerCase().includes(query.toLowerCase()) && (status === 'all' || p.active === (status === 'active')) && (categoryFilter === 'all' || p.category === categoryFilter)), [products, query, status, categoryFilter])
  const loginSubmit = async (event: FormEvent) => { event.preventDefault(); setLoading(true); try { const { data, error: authError } = await createSupabaseClient().auth.signInWithPassword(login); if (authError) throw authError; if (!isAdmin(data.user?.app_metadata)) throw new Error('Esta conta não tem acesso administrativo.'); setLogged(true); await load() } catch (cause) { say(cause instanceof Error ? cause.message : 'Falha no login.', true) } finally { setLoading(false) } }
  const saveProduct = async (event: FormEvent) => { event.preventDefault(); if (!form || !form.name.trim()) return; setLoading(true); try { const saved = editing ? await updateProduct(editing.id, form) : await createProduct(form); setProducts((all) => editing ? all.map((item) => item.id === saved.id ? saved : item) : [saved, ...all]); setForm(null); setEditing(null); say('Produto salvo com sucesso.') } catch (cause) { say(cause instanceof Error ? cause.message : 'Não foi possível salvar.', true) } finally { setLoading(false) } }
  if (!ready) return <main className="admin-shell admin-center"><LoaderCircle className="admin-spinner" /> Preparando painel...</main>
  if (!isSupabaseConfigured) return <main className="admin-shell admin-center"><img src="/Logo PNG Caramelo.png" alt="Finessência" className="admin-logo" /><h1>Conecte o Supabase</h1><p>Adicione as variáveis do arquivo .env.local.</p></main>
  if (!logged) return <main className="admin-shell admin-center"><form className="admin-login" onSubmit={loginSubmit}><img src="/Logo PNG Caramelo.png" alt="Finessência" className="admin-logo" /><p className="admin-eyebrow">ÁREA RESTRITA</p><h1>Entrar</h1><label>E-mail<input className="admin-input" type="email" required value={login.email} onChange={(e) => setLogin({ ...login, email: e.target.value })} /></label><label>Senha<input className="admin-input" type="password" required value={login.password} onChange={(e) => setLogin({ ...login, password: e.target.value })} /></label><button className="admin-button" disabled={loading}>Entrar</button></form>{message && <Toast text={message} error={error} />}</main>
  const title = view === 'products' ? 'Produtos' : view === 'categories' ? 'Categorias' : view === 'essences' ? 'Essências' : 'Efeitos'
  return <main className="admin-shell"><header className="admin-header"><a href="/"><img src="/Logo PNG Caramelo.png" alt="Finessência" className="admin-logo" /></a><button className="admin-text-button" onClick={async () => { await createSupabaseClient().auth.signOut(); setLogged(false) }}><LogOut size={15} /> Sair</button></header><section className="admin-content"><nav className="admin-tabs"><button className={view === 'products' ? 'is-current' : ''} onClick={() => setView('products')}><FolderTree size={16} /> Produtos</button><button className={view === 'categories' ? 'is-current' : ''} onClick={() => setView('categories')}><FolderTree size={16} /> Categorias</button><button className={view === 'essences' ? 'is-current' : ''} onClick={() => setView('essences')}><Sparkles size={16} /> Essências</button><button className={view === 'effects' ? 'is-current' : ''} onClick={() => setView('effects')}><SlidersHorizontal size={16} /> Efeitos</button></nav><div className="admin-title-row"><div><p className="admin-eyebrow">{view === 'effects' ? 'IDENTIDADE VISUAL' : 'CATÁLOGO'}</p><h1>{title}</h1><p>{view === 'products' ? 'Organize as criações que aparecem na sua vitrine.' : view === 'effects' ? 'Ajuste os elementos decorativos da abertura.' : 'Gerencie as opções que aparecem nos produtos.'}</p></div>{view === 'products' && <button className="admin-button" onClick={() => { setEditing(null); setForm(blank) }}><Plus size={16} /> Adicionar produto</button>}</div>{view === 'products' ? <Products products={products} categories={categories} filtered={filtered} query={query} status={status} categoryFilter={categoryFilter} setQuery={setQuery} setStatus={setStatus} setCategoryFilter={setCategoryFilter} onEdit={(p) => { setEditing(p); setForm({ name:p.name, description:p.description ?? '', price:p.price, category:p.category ?? '', essence:p.essence ?? '', detail:p.detail ?? '', active:p.active, imageUrl:p.imageUrl }) }} onDelete={async (p) => { if (!window.confirm(`Excluir “${p.name}”?`)) return; await deleteProduct(p.id); setProducts(products.filter((item) => item.id !== p.id)); say('Produto excluído.') }} onToggle={async (p) => { const saved = await updateProduct(p.id, { name:p.name, description:p.description ?? '', price:p.price, category:p.category ?? '', essence:p.essence ?? '', detail:p.detail ?? '', active:!p.active, imageUrl:p.imageUrl }); setProducts(products.map((item) => item.id === saved.id ? saved : item)) }} /> : view === 'effects' ? <EffectsPanel effects={effects} setEffects={setEffects} /> : <Taxonomies kind={view as TaxonomyKind} items={view === 'categories' ? categories : essences} products={products} setItems={view === 'categories' ? setCategories : setEssences} say={say} />}</section>{form && <ProductForm form={form} setForm={setForm} categories={categories} essences={essences} onClose={() => setForm(null)} onSubmit={saveProduct} loading={loading} />}{message && <Toast text={message} error={error} />}</main>
}

function Products({ products, categories, filtered, query, status, categoryFilter, setQuery, setStatus, setCategoryFilter, onEdit, onDelete, onToggle }: { products:Product[]; categories:Taxonomy[]; filtered:Product[]; query:string; status:string; categoryFilter:string; setQuery:(v:string)=>void; setStatus:(v:string)=>void; setCategoryFilter:(v:string)=>void; onEdit:(p:Product)=>void; onDelete:(p:Product)=>void; onToggle:(p:Product)=>void }) { return <><div className="admin-stats"><Stat label="Total de produtos" value={products.length} /><Stat label="Produtos ativos" value={products.filter((p) => p.active).length} /><Stat label="Produtos inativos" value={products.filter((p) => !p.active).length} /><Stat label="Categorias" value={categories.length} /></div><div className="admin-toolbar"><label className="admin-search"><Search size={17} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar produto..." /></label><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">Todos os status</option><option value="active">Ativos</option><option value="inactive">Inativos</option></select><select value={categoryFilter} onChange={(e) => setCategoryFilter(e.target.value)}><option value="all">Todas as categorias</option>{categories.map((c) => <option key={c.id}>{c.name}</option>)}</select></div><section className="admin-list">{filtered.map((p) => <article className="admin-product" key={p.id}><div className="admin-product-image">{p.imageUrl && <img src={p.imageUrl} alt="" />}</div><div className="admin-product-main"><h2>{p.name}</h2><p>{p.category || 'Sem categoria'}{p.essence && ` · ${p.essence}`}</p><strong>{formatPrice(p.price)}</strong></div><span className={`admin-status ${p.active ? 'is-active' : ''}`}>{p.active ? 'Ativo' : 'Inativo'}</span><time>Atualizado em {new Intl.DateTimeFormat('pt-BR').format(new Date(p.updatedAt))}</time><div className="admin-actions"><button onClick={() => onEdit(p)}><Pencil size={16} /></button><button onClick={() => onToggle(p)}><Sparkles size={16} /></button><button className="is-danger" onClick={() => void onDelete(p)}><Trash2 size={16} /></button></div></article>)}</section></> }
function Taxonomies({ kind, items, products, setItems, say }: { kind:TaxonomyKind; items:Taxonomy[]; products:Product[]; setItems:(v:Taxonomy[])=>void; say:(t:string,b?:boolean)=>void }) { const [name,setName]=useState(''), [editing,setEditing]=useState<Taxonomy|null>(null); const label=kind==='categories'?'categoria':'essência'; const save=async(e:FormEvent)=>{e.preventDefault();try{const saved=editing?await updateTaxonomy(kind,editing,name):await createTaxonomy(kind,name);setItems(editing?items.map(i=>i.id===saved.id?saved:i):[...items,saved].sort((a,b)=>a.name.localeCompare(b.name)));setName('');setEditing(null);say('Salvo com sucesso.')}catch(cause){say(cause instanceof Error?cause.message:'Não foi possível salvar.',true)}}; return <div className="admin-taxonomy"><form className="admin-taxonomy-form" onSubmit={save}><label>{editing?'Renomear':'Nova'} {label}<input className="admin-input" value={name} onChange={(e)=>setName(e.target.value)} required /></label><button className="admin-button">{editing?'Salvar':'Adicionar'}</button>{editing&&<button type="button" className="admin-secondary" onClick={()=>{setEditing(null);setName('')}}>Cancelar</button>}</form><section className="admin-taxonomy-list">{items.map((item)=><article key={item.id}><div><h2>{item.name}</h2><p>{products.filter(p=>p[kind==='categories'?'category':'essence']===item.name).length} produto(s) associado(s)</p></div><div className="admin-actions"><button onClick={()=>{setEditing(item);setName(item.name)}}><Pencil size={16}/></button><button className="is-danger" onClick={async()=>{try{await deleteTaxonomy(kind,item);setItems(items.filter(i=>i.id!==item.id));say('Excluído.')}catch(cause){say(cause instanceof Error?cause.message:'Não foi possível excluir.',true)}}}><Trash2 size={16}/></button></div></article>)}</section></div> }
function EffectsPanel({ effects, setEffects }: { effects: FloralEffects; setEffects: (value: FloralEffects) => void }) { const set = (name:keyof FloralEffects, key:keyof FloralControl, value:boolean|number) => setEffects({ ...effects, [name]:{ ...effects[name], [key]:value } }); const controls=(name:keyof FloralEffects,label:string)=><article className="admin-effect-card" key={name}><div><p className="admin-eyebrow">{label}</p><h2>Ramo {label.toLowerCase()}</h2></div><div className="admin-effect-checks"><label><input type="checkbox" checked={effects[name].desktop} onChange={e=>set(name,'desktop',e.target.checked)}/> Desktop</label><label><input type="checkbox" checked={effects[name].mobile} onChange={e=>set(name,'mobile',e.target.checked)}/> Mobile</label></div><label>Transparência <strong>{effects[name].opacity}%</strong><input type="range" min="0" max="35" value={effects[name].opacity} onChange={e=>set(name,'opacity',Number(e.target.value))}/></label><label>Tamanho <strong>{effects[name].scale}%</strong><input type="range" min="60" max="140" value={effects[name].scale} onChange={e=>set(name,'scale',Number(e.target.value))}/></label><label>Orientação <strong>{effects[name].rotation}°</strong><input type="range" min="-45" max="45" value={effects[name].rotation} onChange={e=>set(name,'rotation',Number(e.target.value))}/></label></article>; return <section className="admin-effects"><header><p className="admin-eyebrow">FLORAIS DA ABERTURA</p><h2>Ramos decorativos</h2><p>Controle individual de presença, transparência, tamanho e orientação.</p></header>{controls('large','Direito')}{controls('small','Esquerdo')}<p className="admin-effects-note">As mudanças são salvas automaticamente neste navegador e aparecem na abertura pública ao recarregar a página.</p></section> }
function ProductForm({ form,setForm,categories,essences,onClose,onSubmit,loading }: { form:ProductInput;setForm:(p:ProductInput)=>void;categories:Taxonomy[];essences:Taxonomy[];onClose:()=>void;onSubmit:(e:FormEvent)=>void;loading:boolean }) {
  const [uploading, setUploading] = useState(false)
  const set = (key:keyof ProductInput,value:string|number|boolean|null) => setForm({...form,[key]:value})
  const upload = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; if (!['image/jpeg','image/png','image/webp'].includes(file.type) || file.size > 5 * 1024 * 1024) return; setUploading(true); try { set('imageUrl', await uploadProductImage(file)) } finally { setUploading(false) } }
  return <div className="admin-modal-layer"><section className="admin-modal"><h2>{form.name||'Novo produto'}</h2><form onSubmit={onSubmit}><div className="admin-form-grid"><label>Nome<input className="admin-input" required value={form.name} onChange={e=>set('name',e.target.value)}/></label><label>Preço<input className="admin-input" type="number" step="0.01" value={form.price||''} onChange={e=>set('price',Number(e.target.value))}/></label><label>Categoria<select className="admin-input" value={form.category} onChange={e=>set('category',e.target.value)}><option value="">Sem categoria</option>{categories.map(i=><option key={i.id}>{i.name}</option>)}</select></label><label>Essência<select className="admin-input" value={form.essence} onChange={e=>set('essence',e.target.value)}><option value="">Sem essência</option>{essences.map(i=><option key={i.id}>{i.name}</option>)}</select></label><label>Detalhe<input className="admin-input" value={form.detail} onChange={e=>set('detail',e.target.value)}/></label><label className="admin-switch-label">Visível<input type="checkbox" checked={form.active} onChange={e=>set('active',e.target.checked)}/><span className="admin-switch"/></label><label className="admin-description">Descrição<textarea className="admin-input" rows={4} value={form.description} onChange={e=>set('description',e.target.value)}/></label></div><label className="admin-upload">{form.imageUrl ? <img src={form.imageUrl} alt="Prévia"/> : <><ImagePlus size={26}/><strong>Selecionar imagem</strong><span>JPG, PNG ou WEBP · até 5 MB</span></>}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={upload} disabled={uploading}/></label><div className="admin-form-actions"><button type="button" className="admin-secondary" onClick={onClose}>Cancelar</button><button className="admin-button" disabled={loading||uploading}>{uploading?'Enviando imagem...':'Salvar'}</button></div></form></section></div>
}
function Stat({label,value}:{label:string;value:number}){return <article><strong>{value}</strong><span>{label}</span></article>};function Toast({text,error}:{text:string;error:boolean}){return <div className={`admin-toast${error?' is-error':''}`}>{text}</div>}
